#!/bin/bash
# install figerprint
# doc https://gist.github.com/yvgit2/c02a61d14e8774230151

sudo add-apt-repository ppa:fingerprint/fingerprint-gui 
sudo apt-get update
sudo apt-get install -y libbsapi policykit-1-fingerprint-gui fingerprint-gui

